/**
 * THE SPIDERNOMICON — the spiderscript lexicon.
 *
 * 100 Spiderscript runes, posted as a Twitter thread from 8 May to 25 Dec 2022.
 * Generated by scripts/upload-spidernomicon.ts from the archived thread; the
 * text is his, verbatim. Runes 79–82 were posted as videos (the first
 * Sorceries) and have no still image.
 */

export interface RuneImage {
  url: string;
  width: number;
  height: number;
}

export interface Rune {
  number: number;
  /** As he wrote it: lowercase runes, capitalized High Runes, all-caps Divine Runes. */
  name: string;
  meaning: string;
  /** The first image is the rune; any others are variants he posted alongside it. */
  images: RuneImage[];
  tweetId: string;
  /** ISO date of the tweet. */
  date: string;
}

export interface Sorcery {
  title: string;
  /** Video URL (mp4). */
  src: string;
  poster?: string;
  /** His tweet text, verbatim minus the media link. */
  caption: string;
  /** ISO date of the tweet. */
  date: string;
  tweetId: string;
  width: number;
  height: number;
}

export const THREAD_URL = 'https://x.com/s0ulDirect0r/status/1523323511543975937';

export function tweetUrl(tweetId: string): string {
  return `https://x.com/s0ulDirect0r/status/${tweetId}`;
}

/**
 * The Sorceries: short videos from June 2022 to March 2023 animating the runes,
 * in chronological order. The "Sorceries" section on /spidernomicon renders
 * only when this list is non-empty.
 *
 * Still empty: the 19 videos are staged locally (scratchpad/tweets/videos,
 * 2022-06-12 … 2023-03-15) and the upload to Blob was not run from the agent
 * session. To fill this in, run scripts/upload-sorceries.ts (see its header).
 */
// --- sorceries: generated by scripts/upload-sorceries.ts ---
export const sorceries: Sorcery[] = [
  {
    title: "Spell of the Sorcerer",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-06-12-spell-of-the-sorcerer.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-06-12-spell-of-the-sorcerer.jpg",
    caption: "UNKNOWN(5125)\n\nSpell of the Sorcerer. What did he just cast into the Multiverse?? What will this spell do, y’all?",
    date: "2022-06-12",
    tweetId: "1535826646908841984",
    width: 1280,
    height: 1280,
  },
  {
    title: "Sorcery #0: The Sorcery of Binding Limits",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-06-25-sorcery-0-the-sorcery-of-binding-limits.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-06-25-sorcery-0-the-sorcery-of-binding-limits.jpg",
    caption: "Sorcery #0: The Sorcery of Binding Limits\n\n“Concentrate on the movement of the runes, and let a limit, previously unseen, come into awareness, feel it, and let it go.” -The Weaver\n\nA prototype sorcery to learn how the spider runes want to be used, deployed, and combined.",
    date: "2022-06-25",
    tweetId: "1540741377834659841",
    width: 1200,
    height: 674,
  },
  {
    title: "Sorcery #1: The Sorcery of Focused Essence",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-06-27-sorcery-1-the-sorcery-of-focused-essence.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-06-27-sorcery-1-the-sorcery-of-focused-essence.jpg",
    caption: "SORCERY #1: The Sorcery of Focused Essence\n\nThe power by which Magicians take felt embodied Essence and Focus it into powerful Artifacts\n\nGaze upon the Sorcery and contemplate its meaning, how does that action express itself through you?\n\n(Runes: Essence X Focus X Magician)",
    date: "2022-06-27",
    tweetId: "1541492366548148226",
    width: 1200,
    height: 674,
  },
  {
    title: "Sorcery #2: The Sorcery of Creative Emergence",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-07-08-sorcery-2-the-sorcery-of-creative-emergence.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-07-08-sorcery-2-the-sorcery-of-creative-emergence.jpg",
    caption: "SORCERY #2: The Sorcery of Creative Emergence\n\nWhat wants to come through you, when you close your eyes and feel the life force of your body? What vibes want to emerge? What’s the web being weaved within the boundless expanse of your soul?\n\nRunes: Artist X Vibe X Web",
    date: "2022-07-08",
    tweetId: "1545472928002850817",
    width: 1200,
    height: 674,
  },
  {
    title: "Spiderscript (animated)",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-08-11-spiderscript-animated.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-08-11-spiderscript-animated.jpg",
    caption: "Redrew and animated the first Spider Rune: ‘Spiderscript’…I feel so much better now having done that cause the OG rune looks so off. May go through the whole tome and redraw and animate all of them, slowly as I find myself in the mood without making a big thing of it.",
    date: "2022-08-11",
    tweetId: "1557633475653640192",
    width: 1280,
    height: 1280,
  },
  {
    title: "The Sorcerer",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-08-15-the-sorcerer.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-08-15-the-sorcerer.jpg",
    caption: "THE SORCERER\n\nFeeling kind of intense about this whole Journey i’m on today. I don’t even know what i’m trying to express with this. Just needed to transmute some feelings and this is what came out. The Deep Unknown is simultaneously wrecking my shit and transforming me.",
    date: "2022-08-15",
    tweetId: "1559096365094952961",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: good vibes",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-09-spell-good-vibes.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-09-spell-good-vibes.jpg",
    caption: "good morning y’all, let’s get’s it. 🤙🏾❤️‍🔥😁\n\na spell for good vibes. may we all have a beautiful day ☺️",
    date: "2022-09-09",
    tweetId: "1568093602273804289",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: eros",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-12-spell-eros.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-12-spell-eros.jpg",
    caption: "good morning y’all. here’s a spell for some eros and sensuality. may all beings get they freak on today 🙏🏾😈❤️‍🔥🫦",
    date: "2022-09-12",
    tweetId: "1569231012718329856",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: alignment",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-13-spell-alignment.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-13-spell-alignment.jpg",
    caption: "good morning y’all. today’s spell is for staying in alignment with the magic and the vibes. i believe in you 😊💖✨",
    date: "2022-09-13",
    tweetId: "1569543685913681924",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: happiness",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-14-spell-happiness.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-14-spell-happiness.jpg",
    caption: "good day y’all. today’s spell is for happiness and a sense of deep okayness. its funny, during the first frame, i caught myself spontaneously vocalizing, and then i just felt really good and OK for the first time in a while. beaming it out to all of you to enjoy. be well, y’all.",
    date: "2022-09-14",
    tweetId: "1570070162736353281",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: unfolding",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-17-spell-unfolding.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-17-spell-unfolding.jpg",
    caption: "good morning y’all. today’s spell is ~unfolding~ may all beings relax and let the Universe unfold as it Will. what does all this evoke in you?",
    date: "2022-09-17",
    tweetId: "1571054330530369537",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: creation",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-20-spell-creation.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-20-spell-creation.jpg",
    caption: "good morning y’all, today’s spell is ~creation~ what does it mean to you to create? you create anything dope lately? share it with me ✨does this evoke anything else?",
    date: "2022-09-20",
    tweetId: "1572094364943536128",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: the anomaly",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-20-spell-the-anomaly.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-20-spell-the-anomaly.jpg",
    caption: "this evening’s spell is ~the anomaly~. i have no idea what this means! i don’t even know what to ask lmao. what does it evoke in y’all? what does an anomaly feel like to ya?",
    date: "2022-09-20",
    tweetId: "1572265864132534275",
    width: 1280,
    height: 1280,
  },
  {
    title: "Spell: transformation",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-25-spell-transformation.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2022-09-25-spell-transformation.jpg",
    caption: "the spell of ~transformation~\n\nwhat does it mean to you to transform? how have you transformed recently or in the past? does the animation evoke anything in you?",
    date: "2022-09-25",
    tweetId: "1574048391096680450",
    width: 1280,
    height: 1280,
  },
  {
    title: "A Daily Sigil",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-01-25-a-daily-sigil.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-01-25-a-daily-sigil.jpg",
    caption: "gm. i was not gonna one of these today, turns out it’s not a good thing to make First, but I finished my daily sigil and I was Chuffed so I did this too 😊",
    date: "2023-01-25",
    tweetId: "1618105994063810560",
    width: 1280,
    height: 1280,
  },
  {
    title: "Flowing Desires",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-02-13-flowing-desires.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-02-13-flowing-desires.jpg",
    caption: "FLOWING DESIRES\n~a digital art exhibition~\n\nI don't know what this is. One could call it an art exhibition. One could call it yet another Sorcery running through me. I just know that I need to do it. It is The Thing that wants to Happen through Me. So here we are.\n\n(9 tweet 🧵)",
    date: "2023-02-13",
    tweetId: "1625227101166260224",
    width: 1280,
    height: 1280,
  },
  {
    title: "Golden Soul",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-02-22-golden-soul.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-02-22-golden-soul.jpg",
    caption: "GOLDEN SOUL: day 10 of 💸 flowing desires 💸\n\ni forged this sigil from a vision i had of being a node in a web of wealth. golden light flowing through me and radiating out towards my friends and loved ones, and from then to those close to them. what will you do with your riches?",
    date: "2023-02-22",
    tweetId: "1628501105280970752",
    width: 1280,
    height: 1280,
  },
  {
    title: "Adventure & Connection",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-02-26-adventure-and-connection.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-02-26-adventure-and-connection.jpg",
    caption: "i was craving adventure & connection with others last night, so sitting in @thesfcommons, i started drawing a sigil from that feeling, and as i finished it people gathered in the room and we talked & i got invited to eat cookies & watch Pride and Prejudice. it was so nice 😌",
    date: "2023-02-26",
    tweetId: "1629911537711452160",
    width: 1280,
    height: 1280,
  },
  {
    title: "Hope",
    src: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-03-15-hope.mp4",
    poster: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/sorceries/2023-03-15-hope.jpg",
    caption: "HOPE\nthis is one of a series of sigils (visual crystallized intentions) i created for a collection I call Flowing Desires, representing with abstract animation my desire and hope to succeed in my creative path.\n\nit desires to be collected for 0.23 ETH\n\nhttps://t.co/a6NyQ9Roy1",
    date: "2023-03-15",
    tweetId: "1635826100554338304",
    width: 1280,
    height: 1280,
  },
];
// --- end sorceries ---

// --- runes: generated by scripts/upload-spidernomicon.ts ---
export const runes: Rune[] = [
  {
    number: 1,
    name: "Spiderscript",
    meaning: "the rune for the script itself. twisting, branching, wavy, and a little random.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-001.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523323511543975937",
    date: "2022-05-08",
  },
  {
    number: 2,
    name: "vibe",
    meaning: "conveys feeling, and magnitude of feeling through color and size",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-002.jpg", width: 800, height: 800 },
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-002-1.jpg", width: 800, height: 800 },
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-002-2.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523347337103364096",
    date: "2022-05-08",
  },
  {
    number: 3,
    name: "word",
    meaning: "a crystallized vibe, the center point marking a particle from which a vibe emanates",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-003.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523430137210961920",
    date: "2022-05-08",
  },
  {
    number: 4,
    name: "love",
    meaning: "a plus sign, representing creativity, flowing out in all directions",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-004.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523447066520739840",
    date: "2022-05-08",
  },
  {
    number: 5,
    name: "self",
    meaning: "a triangle marker, representing a construct, the circle representing a boundary, the points representing traits and characteristics",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-005.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523451778380943361",
    date: "2022-05-08",
  },
  {
    number: 6,
    name: "other",
    meaning: "an inverted triangle, surrounded by a circular boundary, with dots outside of it representing perceived characteristics/traits",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-006.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523481115419234304",
    date: "2022-05-09",
  },
  {
    number: 7,
    name: "body",
    meaning: "a tree like structure, bearing three marks, the construct triangle in the root, the generative plus in the heart, the dot of character at the head",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-007.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523531566000918528",
    date: "2022-05-09",
  },
  {
    number: 8,
    name: "mind",
    meaning: "waves with all possible marks available if you read between the lines. flowing conceptual space.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-008.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523535132275093504",
    date: "2022-05-09",
  },
  {
    number: 9,
    name: "bodymind",
    meaning: "at first i thought this would be a phrase, but, h/t to watching how @embryosophy uses it, this feels like it's a word of it's own. wavy, conceptual space weaved together with a deeply rooted, branching construct",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-009.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523537756542054400",
    date: "2022-05-09",
  },
  {
    number: 10,
    name: "soul",
    meaning: "a wave with a bit of inherent character. the bits of genius that come with every soul that enters the world. not even gonna front like i totally get this one. that's just what it is =/",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-010.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523539529788928007",
    date: "2022-05-09",
  },
  {
    number: 11,
    name: "dopeness",
    meaning: "a critical concept to the structural awesomeness of the Universe. a star, bound in a circle, emitting waves and artifact constructs",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-011.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523703271726084099",
    date: "2022-05-09",
  },
  {
    number: 12,
    name: "action",
    meaning: "a movement of energy in a bounded, defined field emitting change, constructs, traits",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-012.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523712497169039364",
    date: "2022-05-09",
  },
  {
    number: 13,
    name: "void",
    meaning: "expressing the absence of objects with a bound minus",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-013.jpg", width: 800, height: 800 },
    ],
    tweetId: "1523713550929211392",
    date: "2022-05-09",
  },
  {
    number: 14,
    name: "fear",
    meaning: "a minus with a warped boundary. i think the dot is trauma energy warping what would other wise be 'void'. i think. again, i just write this shit y'all :P",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-014.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523892582958391296",
    date: "2022-05-10",
  },
  {
    number: 15,
    name: "magic",
    meaning: "the lightning bolt of energy, mixed with a plus (and an unseen minus), vibing out towards a manifested construct",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-015.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523893756256133120",
    date: "2022-05-10",
  },
  {
    number: 16,
    name: "death",
    meaning: "oh! a new mark has appeared! a skull over a minus. a mortal removed from the board",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-016.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523897983296700417",
    date: "2022-05-10",
  },
  {
    number: 17,
    name: "life",
    meaning: "a skull over a plus with some waves. a mortal, brought forth from love.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-017.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523898796018601984",
    date: "2022-05-10",
  },
  {
    number: 18,
    name: "god",
    meaning: "god, not God. the creative plus, over the energizing bolt, presiding over the mortal principle, in between snaky, rooted waves of mind forming a tower to divine realms",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-018.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523901289804886016",
    date: "2022-05-10",
  },
  {
    number: 19,
    name: "sound",
    meaning: "a word vibrating through a wave and becoming an observable construct (with the ears and body, of course.)",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-019.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523991732869754880",
    date: "2022-05-10",
  },
  {
    number: 20,
    name: "smell",
    meaning: "a construct emitting a few vertically aligned waves. a stanky object 😂",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-020.jpg", width: 400, height: 400 },
    ],
    tweetId: "1523993896304357377",
    date: "2022-05-10",
  },
  {
    number: 21,
    name: "breath",
    meaning: "a positive wave unfolding into a vibe\na vibe unfolding into a negative wave\njoined by a point, a moment in spacetime",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-021.jpg", width: 800, height: 800 },
    ],
    tweetId: "1524570613553135617",
    date: "2022-05-12",
  },
  {
    number: 22,
    name: "growth",
    meaning: "a construct, vibing upwards and outwards",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-022.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1525865475078361089",
    date: "2022-05-15",
  },
  {
    number: 23,
    name: "spider",
    meaning: "a little more complex. waves, circles, points, and a marker of mortality denoting it as a willed creature. it protects a 'mystery'\nspiders are the keepers and weavers of secrets and mysteries in the context of spiderscript",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-023.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1525869202082439168",
    date: "2022-05-15",
  },
  {
    number: 24,
    name: "secret",
    meaning: "a spider came along and bound a mystery, but it still vibes, and attracts little vibes towards it",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-024.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1525872400247578625",
    date: "2022-05-15",
  },
  {
    number: 25,
    name: "web",
    meaning: "hoo boy. this is a deep, powerful rune. there's an idea, enclosed in a bound construct, from the boundary a vibe spirals out, and from the constructed idea, flows waves, connecting ideas (or constructs!) a web can be a series of connected runes, ideas...it's a complex.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-025.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1525914145953964033",
    date: "2022-05-15",
  },
  {
    number: 26,
    name: "peace",
    meaning: "this one took a lot of concentration to weave. feels mad powerful to me. a wavy 8-limbed tree, bearing the mark of infinity, with points (ideas) as fruits at the end of every limb. multiple plus radicals indicating the rune's nourishing, creative, expansive energy",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-026.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1526629752370364416",
    date: "2022-05-17",
  },
  {
    number: 27,
    name: "awakening",
    meaning: "this one came to me in a dream. it shares an overall vibe with the 'god' rune. a mortal rises in being, lifted with energy, expansion, and mystery. i don't know what to say about the background. a shift in perspective? i just draw this shit 🤷🏿‍♂️",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-027.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1527215907625308161",
    date: "2022-05-19",
  },
  {
    number: 28,
    name: "allness",
    meaning: "the rune of the Great Web, of the Universe, of God. an expression of the totality of the universe and all possibilities and all things vibing in and vibing out on different wavelengths. overwhelming and expansive.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-028.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1527342131660017666",
    date: "2022-05-19",
  },
  {
    number: 29,
    name: "fire",
    meaning: "a vibe positioned over an energized construct. representative of the emittance of heat from a burning object.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-029.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1528394453810937863",
    date: "2022-05-22",
  },
  {
    number: 30,
    name: "water",
    meaning: "waves. flows. that's it.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-030.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1528399892342636544",
    date: "2022-05-22",
  },
  {
    number: 31,
    name: "essence",
    meaning: "this one kinda just barged into my awareness and demanded i weave it first today. starting with the bolt of energy vibing out from it's center and curling back on itself with a little idea floating above. i think these types of runes want to be known as 'High Runes'",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-031.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1528777119517376512",
    date: "2022-05-23",
  },
  {
    number: 32,
    name: "air",
    meaning: "honestly, i think it speaks for itself lol. waves with lots of open space in between. carrying faint hints of thought.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-032.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1528780824421621760",
    date: "2022-05-23",
  },
  {
    number: 33,
    name: "earth",
    meaning: "a big construct, containing other constructs, with little waves growing out from it. solid, supportive energy.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-033.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1528790066440462337",
    date: "2022-05-23",
  },
  {
    number: 34,
    name: "ghost",
    meaning: "apparently ghosts are real enough to my imagination that they require a rune in the lexicon. i've always been ambivalent to the idea, but maybe i should reconsider it?\n\na mortal's unbound essence, vibing into (or out of?) a mystery",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-034.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1529122244932251649",
    date: "2022-05-24",
  },
  {
    number: 35,
    name: "yes",
    meaning: "the additive, creative plus, vibing out and curlin'. like any vibe-based rune, it can spiral out further to express a bigger yes",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-035.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1529127185113436160",
    date: "2022-05-24",
  },
  {
    number: 36,
    name: "no",
    meaning: "a bound minus, the subtractive, negative (negative != bad!!) element, emitting a vibe. the no is bound to indicate the setting of a...boundary. it can vibe bigger to express a bigger no and set a bigger boundary.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-036.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1529128474010562560",
    date: "2022-05-24",
  },
  {
    number: 37,
    name: "gift",
    meaning: "find myself desiring to Give more and more. this one came through different. saw myself breathing energy into my hands, and this rune appeared in them. a vibing construct, containing a thought, bound so it can be given. the gift continues to vibe through the boundary.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-037.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1529483412213420032",
    date: "2022-05-25",
  },
  {
    number: 38,
    name: "time",
    meaning: "i don't know man, don't even ask me about this one, decide for yourself ⏳",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-038.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1529490306512498689",
    date: "2022-05-25",
  },
  {
    number: 39,
    name: "success",
    meaning: "lotta High Runes flowing through. had a breakthrough in my relationship to 'Success' yesterday and so its rune appears. a tree of light, blooming with wealth constructs. life-giving waves flowing out from the ground the tree rests in.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-039.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1530236173204852736",
    date: "2022-05-27",
  },
  {
    number: 40,
    name: "sex",
    meaning: "whoa. well, wasn't expecting that. damn i find this one kind of hot. um. lot of polarity waves meeting up, and getting down. emanating golden constructs. not totally sure what that means. High Runes have their own logic i haven't figured out yet 😅",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-040.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1530241786316132353",
    date: "2022-05-27",
  },
  {
    number: 41,
    name: "limit",
    meaning: "a necessary part of living in the world. a construct (acknowledging the Reality of limits) containing a bound thought/idea. (many limits are often perceptual. i suppose.)",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-041.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1530599430180638720",
    date: "2022-05-28",
  },
  {
    number: 42,
    name: "Freedom",
    meaning: "(i'm gonna start capitalizing High Runes)\na concept, breaking free of it's boundary and vibing out of the multidimensional construct (i need to define this 6 pointed star construct at some point) and giving birth to many new thoughts and ideas. i love this one a lot",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-042.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1530603854605168642",
    date: "2022-05-28",
  },
  {
    number: 43,
    name: "money",
    meaning: "i'm going to stop explaining the logic behind these. what does want to be said in its place, what it means to me? a store of value, valuable in itself, enabling access to other valuable entities.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-043.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1530962354866753537",
    date: "2022-05-29",
  },
  {
    number: 44,
    name: "light",
    meaning: "superpositioned wave-particles blasting out in all directions throughout the known Universe, illuminating reality for our enjoyment and navigation",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-044.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1531295086394286080",
    date: "2022-05-30",
  },
  {
    number: 45,
    name: "Creativity",
    meaning: "inspired by last night's dream (and the charge that ran through my body as i woke from it)...and my growing resonance with this vibe. the dance of energy and creation between the cosmic forces of the Universe and us mortals",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-045.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1532036918636032000",
    date: "2022-06-01",
  },
  {
    number: 46,
    name: "spirit",
    meaning: "a concept, a vibe, that's taken on a life of it's own and moves and flows through the mythomemetic layer of reality",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-046.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1533501353426702336",
    date: "2022-06-05",
  },
  {
    number: 47,
    name: "story",
    meaning: "a transmission between mortals of waves, vibes, ideas, translated through mystery",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-047.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1533505851033411584",
    date: "2022-06-05",
  },
  {
    number: 48,
    name: "artist",
    meaning: "a mortal, communicating and receiving the vibes of the spirits that enter it's boundary, outputting artifacts and constructs from the interaction",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-048.jpg", width: 1200, height: 1200 },
    ],
    tweetId: "1533510340247375872",
    date: "2022-06-05",
  },
  {
    number: 49,
    name: "wand",
    meaning: "in the world of spider script, a wand refers to any implement or tool used to channel creative energy, a pen, a staff, a grimoire…if it allows you to wield your powers, that’s all that matters",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-049.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1534570192654594048",
    date: "2022-06-08",
  },
  {
    number: 50,
    name: "weapon",
    meaning: "whatever you need to protect yourself and your boundaries, weaver.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-050.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1534572345741832193",
    date: "2022-06-08",
  },
  {
    number: 51,
    name: "snake",
    meaning: "snakes traverse the wastelands as well. they pursue and hunt spirits and like to find pockets of wild, free magic to wrap themselves around. sorcerers and weavers have found their venom a powerful ink for runeweaving. beware, their bite will dissolve your bodymind.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-051.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1534934170639556612",
    date: "2022-06-09",
  },
  {
    number: 52,
    name: "venom",
    meaning: "the venom of the wasteland’s astral-beasts is extremely dangerous and potent. if extracted and treated and integrated skillfully, can unlock stupendous power in the imbiber. otherwise it just destroys living and spiritual beings in the most agonizing ways.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-052.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1534953742121938944",
    date: "2022-06-09",
  },
  {
    number: 53,
    name: "despair",
    meaning: "well, I was trying to do Hope but I couldn’t, and I got hint I needed to weave this first for it to have any meaning. so yeah. y’all know exactly what this is. it be like that sometimes. the wastelands ain’t for the faint of heart.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-053.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1535288109411102720",
    date: "2022-06-10",
  },
  {
    number: 54,
    name: "system",
    meaning: "the processes that emerge and propagate throughout civilization, nature, and the Universe. they are impermanent and changeable, moving through and to the mortals that wield or are wielded by them for wholesome or unwholesome ends.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-054.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1535415751896465409",
    date: "2022-06-11",
  },
  {
    number: 55,
    name: "portal",
    meaning: "this feels like very powerful to me. a sacred portal, powered by the elements and the infinite mystery. a path in and out of wonder and madness and adventure. be not afraid. step through whenever you see one. discover the gifts that await.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-055.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1535675925810950144",
    date: "2022-06-11",
  },
  {
    number: 56,
    name: "Hope",
    meaning: "The power of optimism in its fullest, reaching out to as many beings as it can, opening them up to life and love. The Cross has power even in the Wastelands.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-056.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1536391453458305025",
    date: "2022-06-13",
  },
  {
    number: 57,
    name: "artifact",
    meaning: "fruits of the UNKNOWN machine. crystallized objects and expressions of power & dopeness. this was a stubborn rune. took a lot of reworking to get it to completion-activation.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-057.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1536436100536750081",
    date: "2022-06-13",
  },
  {
    number: 58,
    name: "star",
    meaning: "the great and beautiful celestial objects that populate the night sky. bombarding all of us with their life giving rays. not even the wastelands are excused from their glory.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-058.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1536740741883387905",
    date: "2022-06-14",
  },
  {
    number: 59,
    name: "music",
    meaning: "there’s a lot going on but I kinda love it. a musician emanates a great web of sound and good vibes, easing the beings it reaches and attracting curious friendly spirits to partake in the occasion.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-059.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1536751667760091137",
    date: "2022-06-14",
  },
  {
    number: 60,
    name: "voice",
    meaning: "the power granted to all beings to take their energy and vibes and crystallize and externalize them out into the world.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-060.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1536755986408427520",
    date: "2022-06-14",
  },
  {
    number: 61,
    name: "Patience",
    meaning: "an essential quality of any successful spider, snake, or Magician. weave your web, wait for your moment, know that good things are coming, as long as you’re prepared and open.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-061.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537201635125891072",
    date: "2022-06-15",
  },
  {
    number: 62,
    name: "river",
    meaning: "a flowing current of water and energy, carrying life giving waters far and wide, flow, flow, flow you magicians and weavers",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-062.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537450648471367683",
    date: "2022-06-16",
  },
  {
    number: 63,
    name: "dance",
    meaning: "sacred art of arts, aligning oneself with life, love, vibes and moving together with it all as once. no Magician is complete without a relationship with this power.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-063.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537454612386439168",
    date: "2022-06-16",
  },
  {
    number: 64,
    name: "Wonder",
    meaning: "the End that true Magicians are always moving towards. being living channels of this power in the world and the wasteland. how much do your artifacts activate and expand the life force? do your works fill the Multiverse with inspiration and enthusiasm?",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-064.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537839907632123905",
    date: "2022-06-17",
  },
  {
    number: 65,
    name: "power",
    meaning: "a tool in the Magician’s belt. can be wielded for good or ill. comes in many forms and flavors. what kind of power do you seek, and for what ends?",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-065.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537854503939997696",
    date: "2022-06-17",
  },
  {
    number: 66,
    name: "angel",
    meaning: "divine intelligences pass through the wastelands from time to time. if you call to them, they will come. powerful and mysterious, they lovingly, if not a bit intensely, enact change on the behalf of mortals and Magicians.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-066.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537935363649380353",
    date: "2022-06-17",
  },
  {
    number: 67,
    name: "demon",
    meaning: "beware the demons of the wastelands!! they will enslave your soul and use it to power their magics until there is nothing left! the Weaver of this lexicon barely survived his own encounter to forge this rune so that others may be empowered and protected!",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-067.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1537994832659943424",
    date: "2022-06-18",
  },
  {
    number: 68,
    name: "space",
    meaning: "the container in which all the worlds and stars and energy are held in the physical dimension. the Weaver was surprised by infinity not showing up in this rune. brings up questions about infinity and eternity for future runes and scripts…",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-068.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1538918721116262400",
    date: "2022-06-20",
  },
  {
    number: 69,
    name: "pain",
    meaning: "a reality that all beings that traverse the wastelands must face. the sharp cuts, physical, mental, or emotional that life inflicts to teach. with resilience, and soul, one may transmute it into more Life.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-069.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539275535645147138",
    date: "2022-06-21",
  },
  {
    number: 70,
    name: "pleasure",
    meaning: "often awaiting us on the other side of pain. a critical fuel of the soul, sustaining the will to Live. the tickles and kisses and caresses of Life to nourish and encourage",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-070.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539278188685037570",
    date: "2022-06-21",
  },
  {
    number: 71,
    name: "focus",
    meaning: "the core skill of the magicians of the wastelands. the concentration of curious attention on meaningful, interesting artifacts so as to merge with them and gain access to wisdom and ever-powerful sorceries",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-071.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539686351339405312",
    date: "2022-06-22",
  },
  {
    number: 72,
    name: "magician",
    meaning: "a living being that seeks truth, power, and Wonder through focused, diligent meditation and contemplation in unison with persistent adventuring and journeying across the many dimensions. sometimes casts spells to aid in the above :)",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-072.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539687074004996097",
    date: "2022-06-22",
  },
  {
    number: 73,
    name: "heart",
    meaning: "the portal that connects living beings and Magicians to the dimension of the Agape. the more attuned the enheartened is, the more Divine Love can flow through them into all worlds.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-073.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539742983251103748",
    date: "2022-06-22",
  },
  {
    number: 74,
    name: "abyss",
    meaning: "the Underworld. the source of all Mystery, the point from which it emanates. the portals are everywhere if you know where to look. there isn’t a point in looking though. all beings must face the Abyss one day, when it has called them.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-074.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539743922901069826",
    date: "2022-06-22",
  },
  {
    number: 75,
    name: "blood",
    meaning: "life giving liquid flow that powers the bodies of living mortal beings. powerful, when used wisely. best to generally keep it inside the body though.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-075.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539993300886687745",
    date: "2022-06-23",
  },
  {
    number: 76,
    name: "semen",
    meaning: "concentrated life force, even more potent than the blood. the great fertilizer, channeled into the right vessel, creates great generative blooms.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-076.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1539997955888799744",
    date: "2022-06-23",
  },
  {
    number: 77,
    name: "egg",
    meaning: "the great vessel, from which beings enter the physical plane. pure potential, waiting to be hatched and unleashed into the World",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-077.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1540000182456049664",
    date: "2022-06-23",
  },
  {
    number: 78,
    name: "World",
    meaning: "The shape of reality, the many dimensions, the many layers of existence, infinitely deep and eternally long. The great playground where all players, magicians, and beings converge.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-078.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1540006753873428480",
    date: "2022-06-23",
  },
  {
    number: 79,
    name: "The Sorcery of Focused Essence",
    meaning: "From this point on, the Runes shall now be wielded and combined to create the Sorceries.",
    images: [],
    tweetId: "1541493245678563328",
    date: "2022-06-27",
  },
  {
    number: 80,
    name: "THE SORCERY OF CREATIVE EMERGENCE",
    meaning: "",
    images: [],
    tweetId: "1545816156002467842",
    date: "2022-07-09",
  },
  {
    number: 81,
    name: "The Invitation of Allness",
    meaning: "",
    images: [],
    tweetId: "1547232105947693057",
    date: "2022-07-13",
  },
  {
    number: 82,
    name: "The Mystery of Ensoulment",
    meaning: "",
    images: [],
    tweetId: "1547943301369606150",
    date: "2022-07-15",
  },
  {
    number: 83,
    name: "SORCERY #5 - THE HEART OF GOD",
    meaning: "What does the Heart of God feel like to you? What does it evoke in your bodymind?\n\nRunes: Love X Patience X Heart\n\n(this one is downrezzed to fit Twitter’s video requirements so it should look better)",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-083.jpg", width: 1920, height: 1080 },
    ],
    tweetId: "1556630346648719360",
    date: "2022-08-08",
  },
  {
    number: 84,
    name: "GRATITUDE",
    meaning: "first of the Divine Runes, standing above even the High Runes. the power of Gratitude is one of the most divine powers available to a sorcerer. in seeing and acknowledging the glory of the Divine in all things, sorcerers may attain even greater levels of divinity",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-084.jpg", width: 1800, height: 1800 },
    ],
    tweetId: "1589965528441188357",
    date: "2022-11-08",
  },
  {
    number: 85,
    name: "CHAOS",
    meaning: "the grand force of disorder. a spacetime whirlwind that keeps the Game of Reality fresh and interesting. to deny the Chaos of the World is to set oneself up for disappointment and frustration. to embrace it, is to live in Wonder, surprise, change, and flow.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-085.jpg", width: 1800, height: 1800 },
    ],
    tweetId: "1598063742159564802",
    date: "2022-11-30",
  },
  {
    number: 86,
    name: "LIGHTNING",
    meaning: "the legendary symbol of divine might, the lightning bolt. striking fear and awe into the hearts of humans since the dawn of time. when inspiration strikes, it’s often said to feel like being struck by lightning. it’s true. ride the lightning.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-086.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1604331105879961600",
    date: "2022-12-18",
  },
  {
    number: 87,
    name: "IMAGINATION",
    meaning: "the divine sight granted to all humans, the power of imagination, the ability to see beyond the physical plane. the power to visualize, envision, imagine, sense beyond the limits of the body. a necessary faculty of sorcerers to contact the Eternal.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-087.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1604362154395607041",
    date: "2022-12-18",
  },
  {
    number: 88,
    name: "SIGIL",
    meaning: "the divine artifact. an intention crystallized in a visual interactive form, with the power to direct magic and energy towards the creation of a phenomenon. from the Mystery, to the Imagination, and through the hands of a living vessel a Sigil is wrought.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-088.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1604591538260303872",
    date: "2022-12-18",
  },
  {
    number: 89,
    name: "PASSION",
    meaning: "the violet flame of inspiration and madness in equal measure. it is fickle, whimsical, dangerous…and that’s what’s most beautiful and powerful about it. art, war, romance…the most intense parts of being alive arise forged in this fire.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-089.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1604958700673720322",
    date: "2022-12-19",
  },
  {
    number: 90,
    name: "PROPHECY",
    meaning: "from the realm of the Eternal, the dimension of the mythopoetic, divine inspiration strikes the Magician, and through them flows into the world. divine knowledge meant to unleash the immanence inherent to the living.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-090.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1604964775913328640",
    date: "2022-12-19",
  },
  {
    number: 91,
    name: "BEAST",
    meaning: "the dark force of survival. when the chips are down, and it’s you vs. Death, the final power a sorcerer may call upon. the lineage must not be broken. survive and pass down the genes, the memes, and the runes for the next generation to wield.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-091.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1605731336890634241",
    date: "2022-12-22",
  },
  {
    number: 92,
    name: "AWARENESS",
    meaning: "just be with what’s alive right now. what are you aware of in this moment? in this image? in your body? in the space around you? immerse yourself.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-092.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1605743827985108992",
    date: "2022-12-22",
  },
  {
    number: 93,
    name: "DEVOTION",
    meaning: "the Divine Power that unlocks miracles for sorcerers who are willing to Listen and Read the Flow. a grand compounding force, as one’s Devotion grows, the magnitude of miracles that may occur rises exponentially. the Weaver of this tome can attest to its potency.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-093.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1605759257277739008",
    date: "2022-12-22",
  },
  {
    number: 94,
    name: "IMMANENCE",
    meaning: "the light that blooms from within. the means by which the soul’s divinity is fully embodied and actualized in the World. the path by which a mortal, becomes a sorcerer, then a god, and then reunites with the Mystery",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-094.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606075464736329728",
    date: "2022-12-22",
  },
  {
    number: 95,
    name: "FORGIVENESS",
    meaning: "the means by which all beings, sorcerers or not, are freed from the shackles of karma, allowing their spirits to rise and expand across and through the 666 dimensions",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-095.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606083160894164993",
    date: "2022-12-23",
  },
  {
    number: 96,
    name: "TEMPLE (V2)",
    meaning: "sacred space of silence and soulfulness. where sorcerers go to connect with Divinity and deepen on the path of Immanence. a powerful nexus where one may freely access by the timelessness of Eternity",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-096.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606112029391327232",
    date: "2022-12-23",
  },
  {
    number: 97,
    name: "COMPASSION",
    meaning: "THE DIVINE POWER THAT BRINGS US ALL TOGETHER AND RESTORES MORTAL BEINGS TO WHOLENESS. THE FLAME OF LOVE THAT DISSOLVES SHAME, FEAR, AND DISPELS THE DARKNESS. (this one was loud and would not be denied -Weaver’s Note)",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-097.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606129576366612481",
    date: "2022-12-23",
  },
  {
    number: 98,
    name: "SURRENDER",
    meaning: "the means by which a sorcerer connects with the great Flow of Life, with the Will of the Universe as it unfolds. incredible, infinite power is available to the one who cedes his will in deciding how it is used.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-098.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606221823787401217",
    date: "2022-12-23",
  },
  {
    number: 99,
    name: "DESTINY",
    meaning: "the vectors of life force drawing us all forwards and up. the Sorcerer rides these spears of power towards Godhood, with devotion, compassion, gratitude, and the many, many other powers granted to them.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-099.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606482718845718528",
    date: "2022-12-24",
  },
  {
    number: 100,
    name: "ETERNITY",
    meaning: "The origin and ending of all that is and will be. The root. The center of reality. The Ultimate Portal, The Mystery Beyond, whatever you want to call it doesn’t matter, it just Is and Always Will Be.\n\nWelcome Home, Weaver.",
    images: [
      { url: "https://zp7hauqhmxup1nll.public.blob.vercel-storage.com/spidernomicon/rune-100.jpg", width: 2048, height: 2048 },
    ],
    tweetId: "1606963814662303746",
    date: "2022-12-25",
  },
];
// --- end runes ---
